# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTc5:

    @pytest.fixture(scope='class')
    def driver(self):
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        driver = webdriver.Chrome(options=options)
        yield driver
        driver.quit()

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        driver.set_window_size(1603, 947)
        driver.get("https://guidebook.seleniumacademy.com/Window.html")

    def test_handle_window(self, driver):
        first_window = driver.current_window_handle
        print("Pierwsze okno:", first_window)

        link = driver.find_element(By.LINK_TEXT, "Google Search")
        link.click()

        driver.implicitly_wait(5)

        window_handles = driver.window_handles
        print("Ilość zakładek:", len(window_handles))

        for handle in window_handles:
            if handle != first_window:
                second_window = handle
                break

        driver.switch_to.window(second_window)
        print("Druga zakładka", second_window)

        driver.switch_to.window(first_window)
        print("Powrót do pierwszej zakładki")
