# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTc6:

    @pytest.fixture(scope='class')
    def driver(self):
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        driver = webdriver.Chrome(options=options)
        yield driver
        driver.quit()

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        driver.set_window_size(1603, 947)
        driver.get("https://guidebook.seleniumacademy.com/Frames.html")
        driver.implicitly_wait(5)

    def test_switch_between_frames(self, driver):
        driver.switch_to.frame(0)
        first_field = driver.find_element(By.NAME, '1')
        first_field.send_keys("Jest w jedynce")
        driver.save_screenshot("Jedynka.png")
        driver.switch_to.default_content()

        driver.switch_to.frame(1)
        second_field = driver.find_element(By.NAME, "2")
        second_field.send_keys("Jest w dwójce")
        driver.save_screenshot("Dwojka.png")
