# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTc2:

    @pytest.fixture(scope='class')
    def driver(self):
        options = webdriver.ChromeOptions()
        options.add_argument('--headless')
        driver = webdriver.Chrome(options=options)
        yield driver
        driver.quit()

    @pytest.fixture(autouse=True)
    def setup(self, driver):
        driver.set_window_size(1603, 947)
        driver.get("http://demo-store.seleniumacademy.com/")

    @pytest.mark.parametrize(
        "search_term, expected_title", [
            pytest.param("blazer", "Search results for: 'blazer'", id="wyszukuje blazer"),
            pytest.param("shirts", "Search results for: 'shirts'", id="wyszukuje shirts"),
            pytest.param("skirt", "Search results for: 'skirt'", id="wyszukuje skirt"),
        ]
    )
    def test_search(self, driver, search_term, expected_title):
        driver.find_element(By.ID, "search").send_keys(search_term)
        driver.find_element(By.CSS_SELECTOR, ".search-button").click()
        assert driver.title.lower() == expected_title.lower()

    def test_by_link_text(self, driver):
        my_acc_link = driver.find_element(By.PARTIAL_LINK_TEXT, "MY")
        my_acc_link.click()
        assert driver.title == 'Customer Login'

    def test_by_tag_locator(self, driver):
        links = driver.find_elements(By.TAG_NAME, "a")
        print(f"Znaleziono: {len(links)}")
        for e in links:
            if e.text:
                print(e.text)

    def test_element_get_atrr(self, driver):
        search_box = driver.find_element(By.NAME, 'q')
        print("Atrybut name:", search_box.get_attribute("name"))
        print("Atrybut Id:", search_box.get_attribute("id"))
        print("Atrybut Placeholder:", search_box.get_attribute("placeholder"))

    def test_get_text(self, driver):
        site_notice = driver.find_element(By.CLASS_NAME, "global-site-notice")
        print("Tekst z klasy:", site_notice.text)

    def test_get_css_value(self, driver):
        search_box = driver.find_element(By.NAME, 'q')
        font_family = search_box.value_of_css_property("font-family")
        print("Font w boxie:", font_family)

    def test_get_location(self, driver):
        search_box = driver.find_element(By.NAME, 'q')
        location = search_box.location
        print("Lokalizacja elementu", location)

    def test_get_size(self, driver):
        search_box = driver.find_element(By.NAME, 'q')
        size = search_box.size
        print("Rozmiar elementu", size)

    def test_get_tag_name(self, driver):
        search_button = driver.find_element(By.CLASS_NAME, "search-button")
        tag_name = search_button.tag_name
        print("Tag w którym znajduje się element:", tag_name)
